#pragma once

#define NODE_BOARD_NAME "B-G431B-ESC1"
#define NODE_DEFAULT_ID 0x11
#define NODE_RPM_MIN 500
#define NODE_RPM_MAX 3000
#define NODE_CURRENT_LIMIT_CONT_A 20
#define NODE_CURRENT_LIMIT_PEAK_A 35
#define NODE_TEMP_LIMIT_C 85
#define NODE_STATUS_PERIOD_MS 20
#define NODE_HEARTBEAT_PERIOD_MS 100
